name: Scala CLA
on: 
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./project/scripts/check-cla.sh
      env:
        AUTHOR: ${{ github.event.pull_request.user.login }}
